# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: 0.6
    - julia: nightly
notifications:
  email: false
after_success:
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("DASSL")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
  # push coverage results to Codecov
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("DASSL")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'; fi
